os: linux
language: android
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - android-28
jdk: oraclejdk8
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid
install:
- git clone https://github.com/flutter/flutter.git -b stable --depth 1
- "./flutter/bin/flutter doctor"
cache:
  directories:
  - "$HOME/.pub-cache"

# before_deploy:
# Set up git user name and tag this commit
# - git config --local user.name "stefanJi"
# - git config --local user.email "408776303@qq.com"
# - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
# - git tag $TRAVIS_TAG

stages:
  - check
  - test
  - name: depoly
    if: tag =~ /^release-v\d+\.\d+\.\d+/ # tag match: release-v1.0.0

jobs:
  include:
    - stage: check
      script: flutter analyze
    - stage: test
      script: flutter test
    - stage: depoly
      script:
        - "./flutter/bin/flutter build apk"
        - export APK_NAME=$(date +'%Y%m%d%H%M%S')-F4Lab.apk
        - "mv build/app/outputs/apk/release/app-release.apk ${APK_NAME}"
      deploy:
        provider: releases
        api_key:
          secure: $github_deploy_api_key
        file: $APK_NAME
        skip_cleanup: true
        overwrite: true
        on:
          repo: stefanJi/Flutter4GitLab
          branch: master
      
