os: linux
language: android
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
jdk: oraclejdk8
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid
install:
- git clone https://github.com/flutter/flutter.git -b stable --depth 1
- export PATH=$PATH:./flutter/bin
- flutter doctor
cache:
  directories:
  - "$HOME/.pub-cache"

stages:
  - test
  - name: depoly
    if: tag =~ /^release-v\d+\.\d+\.\d+/ # tag match: release-v1.0.0
 
jobs:
  include:
    - stage: test
      script: flutter analyze lib test
      script: flutter test test
    - stage: depoly
      script:
        - flutter build apk
        - export APK_NAME=$(date +'%Y%m%d%H%M%S')-F4Lab.apk
        - "mv build/app/outputs/apk/release/app-release.apk ${APK_NAME}"
      deploy:
        provider: releases
        api_key:
          secure: $github_deploy_api_key
        file: $APK_NAME
        skip_cleanup: true
        overwrite: true
        on:
          repo: stefanJi/Flutter4GitLab
          branch: master
      
